del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\tabbar_facebook_selected.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\tabbar_facebook.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\tabbar_home_selected.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\tabbar_home.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\tabbar_offers_selected.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\tabbar_offers.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\tabbar_stores_selected.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\tabbar_stores.png"
copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\parquetim images\drawable-hdpi\icon.png" "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\icon.png"

del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\tabbar_facebook_selected.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\tabbar_facebook.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\tabbar_home_selected.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\tabbar_home.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\tabbar_offers_selected.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\tabbar_offers.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\tabbar_stores_selected.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\tabbar_stores.png"
copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\parquetim images\drawable-xhdpi\icon.png" "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\icon.png"

copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\parquetim images\drawable-mdpi" "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-mdpi"