copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\zer4u images\drawable-hdpi\icon.png" "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\icon.png"
copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\zer4u images\drawable-mdpi\icon.png" "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-mdpi\icon.png"
copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\zer4u images\drawable-xhdpi\icon.png" "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\icon.png"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\assets\anim.gif"
del "C:\Projects\AndroidMaster\AndroidMaster\Master\assets\anim.htm"