copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\soho images\drawable-hdpi\icon.png" "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-hdpi\icon.png"
copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\soho images\drawable-mdpi\icon.png" "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-mdpi\icon.png"
copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\soho images\drawable-xhdpi\icon.png" "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xhdpi\icon.png"
copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\soho images\drawable-xxhdpi\icon.png" "C:\Projects\AndroidMaster\AndroidMaster\Master\res\drawable-xxhdpi\icon.png"
copy "C:\Users\Shaya\Google Drive\mximo\temp\version configuration\soho images\assets" "C:\Projects\AndroidMaster\AndroidMaster\Master\assets"
